#!/bin/bash

source "$(dirname "$0")"/build-info.sh

build_builder_image() {
    pushd "$(dirname "$0")"/.. > /dev/null
        docker build -t "${BUILDER_IMAGE_NAME}" .
    popd > /dev/null
}

build_builder_image
